'use client';

import React from 'react';

interface Comparison {
  compared_to_candidate_id: string;
  better_aspects: string[];
  worse_aspects: string[];
  justification: string;
}

interface ExplainabilityReportData {
  candidate_id: string;
  job_id: string;
  explanation_type: string;
  summary: string;
  dimension_explanations: Record<string, string>;
  strengths: string[];
  weaknesses: string[];
  interview_focus: string[];
  development_opportunities: string[];
  comparisons: Comparison[];
}

interface ExplanationCardProps {
  report: ExplainabilityReportData | null;
}

export default function ExplanationCard({ report }: ExplanationCardProps) {
  if (!report) {
    return (
      <div className="glass-panel" style={{ textAlign: 'center', padding: '3rem', color: 'var(--color-text-secondary)' }}>
        Select a candidate from the ranking table to view their explainability report.
      </div>
    );
  }

  return (
    <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', borderLeft: '4px solid var(--color-accent-cyan)' }}>
      <div>
        <h3 className="text-glow-cyan" style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--color-accent-cyan)' }}>
          Hiring Rationale & Explanation
        </h3>
        <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.85rem', marginTop: '0.25rem' }}>
          Grounded narrative generated by Explainability Agent (grounded in candidate credentials)
        </p>
      </div>

      <div style={{ background: 'rgba(255,255,255,0.03)', padding: '1rem', borderRadius: '8px', borderLeft: '2px solid var(--color-accent-cyan)' }}>
        <p style={{ fontSize: '0.95rem', lineHeight: '1.6', fontStyle: 'italic' }}>
          &ldquo;{report.summary}&rdquo;
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
        {/* Strengths */}
        <div>
          <h4 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--color-accent-green)', marginBottom: '0.5rem' }}>
            ✓ Top Strengths
          </h4>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.85rem', color: 'var(--color-text-secondary)', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
            {report.strengths && report.strengths.length > 0 ? (
              report.strengths.map((str, idx) => <li key={idx}>{str}</li>)
            ) : (
              <li>High general skills alignment.</li>
            )}
          </ul>
        </div>

        {/* Gaps / Risks */}
        <div>
          <h4 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--color-accent-gold)', marginBottom: '0.5rem' }}>
            ⚠ Gaps & Hiring Risks
          </h4>
          <ul style={{ paddingLeft: '1.25rem', fontSize: '0.85rem', color: 'var(--color-text-secondary)', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
            {report.weaknesses && report.weaknesses.length > 0 ? (
              report.weaknesses.map((weak, idx) => <li key={idx}>{weak}</li>)
            ) : (
              <li>No significant gaps or risks identified.</li>
            )}
          </ul>
        </div>
      </div>

      {/* Comparisons */}
      {report.comparisons && report.comparisons.length > 0 && (
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1rem' }}>
          <h4 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--color-accent-purple)' }}>
            Cohort Comparison Justification
          </h4>
          {report.comparisons.map((comp, idx) => (
            <div key={idx} style={{ fontSize: '0.85rem', color: 'var(--color-text-secondary)', background: 'rgba(124, 77, 255, 0.05)', padding: '0.75rem', borderRadius: '6px', marginTop: '0.5rem' }}>
              <strong>vs Candidate {comp.compared_to_candidate_id.substring(0, 8)}...</strong>
              <p style={{ marginTop: '0.25rem', lineHeight: '1.4' }}>{comp.justification}</p>
            </div>
          ))}
        </div>
      )}

      {/* Interview Focus */}
      <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1rem' }}>
        <h4 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '0.5rem' }}>
          Tailored Interview Focus Questions
        </h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {report.interview_focus && report.interview_focus.length > 0 ? (
            report.interview_focus.map((q, idx) => (
              <div key={idx} style={{ padding: '0.75rem', background: 'rgba(255,255,255,0.02)', borderRadius: '6px', fontSize: '0.85rem', borderLeft: '2px solid var(--color-accent-purple)' }}>
                {q}
              </div>
            ))
          ) : (
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '0.85rem' }}>Conduct standard technical scaling interview.</p>
          )}
        </div>
      </div>

      {/* Development Opportunities */}
      {report.development_opportunities && report.development_opportunities.length > 0 && (
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '1rem' }}>
          <h4 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--color-accent-cyan)' }}>
            Upskilling Recommendations
          </h4>
          <p style={{ fontSize: '0.85rem', color: 'var(--color-text-secondary)', lineHeight: '1.4' }}>
            {report.development_opportunities.join(', ')}
          </p>
        </div>
      )}
    </div>
  );
}
