from typing import List, Optional
from pydantic import BaseModel, Field

class Education(BaseModel):
    degree: str = Field(..., description="E.g., Bachelor of Science, Master's")
    major: str = Field(..., description="E.g., Computer Science")
    institution: str = Field(..., description="University or college name")
    graduation_year: Optional[int] = Field(None, description="Year of graduation")

class Role(BaseModel):
    title: str = Field(..., description="Job title")
    company: str = Field(..., description="Company name")
    start_date: Optional[str] = Field(None, description="Start date (YYYY-MM or YYYY)")
    end_date: Optional[str] = Field(None, description="End date (YYYY-MM or YYYY), 'Present' if current")
    duration_months: Optional[int] = Field(None, description="Calculated duration in months")
    responsibilities: List[str] = Field(default_factory=list, description="Key responsibilities and achievements")
    technologies: List[str] = Field(default_factory=list, description="Technologies used in this role")

class CandidateProfile(BaseModel):
    """
    Core schema representing a parsed candidate resume.
    This is generated by the Candidate Intelligence Agent.
    """
    id: Optional[str] = Field(None, description="Unique candidate ID (UUID)")
    tenant_id: str = Field(..., description="Tenant ID for RLS")
    
    first_name: str = Field(..., description="Candidate's first name")
    last_name: str = Field(..., description="Candidate's last name")
    email: Optional[str] = Field(None, description="Candidate's email address")
    phone: Optional[str] = Field(None, description="Candidate's phone number")
    
    summary: str = Field(..., description="A synthesized summary of the candidate's career")
    
    education: List[Education] = Field(default_factory=list)
    experience: List[Role] = Field(default_factory=list)
    
    hard_skills: List[str] = Field(default_factory=list, description="Technical skills (e.g., Python, AWS)")
    soft_skills: List[str] = Field(default_factory=list, description="Interpersonal skills (e.g., Leadership)")
    
    total_years_experience: float = Field(0.0, description="Calculated total years of experience")
    embedding_text: str = Field("", description="Text representation used for generating embeddings")
