from typing import Optional
from pydantic import BaseModel, Field

class CandidateFeatures(BaseModel):
    """
    Schema for precomputed candidate features persisted in the Feature Store.
    These are the scores generated by the Feature Engineering Pipeline.
    Values are normalized floats between 0.0 and 1.0.
    """
    candidate_id: str = Field(..., description="Foreign key to the candidate profile")
    tenant_id: str = Field(..., description="Tenant ID for RLS")
    
    skill_depth: float = Field(0.0, ge=0.0, le=1.0, description="Overall depth of technical skills")
    career_progression: float = Field(0.0, ge=0.0, le=1.0, description="Trajectory of promotions and responsibility")
    project_complexity: float = Field(0.0, ge=0.0, le=1.0, description="Complexity and impact of projects delivered")
    authenticity: float = Field(0.0, ge=0.0, le=1.0, description="Likelihood the resume is authentic (not AI generated)")
    growth: float = Field(0.0, ge=0.0, le=1.0, description="Demonstrated ability to learn and adapt")
    
    # Metadata
    updated_at: Optional[str] = Field(None, description="ISO timestamp of last update")
