from typing import Optional, List, Dict
from pydantic import BaseModel, Field

class FeatureValue(BaseModel):
    value: float = Field(..., ge=0.0, le=1.0)
    derived_from: List[str] = Field(default_factory=list, description="Lineage of which extraction points drove this score")

class CandidateFeatures(BaseModel):
    """
    Schema for precomputed candidate features persisted in the Feature Store.
    These are the scores generated by the Feature Engineering Pipeline.
    Values are normalized floats between 0.0 and 1.0, wrapped with lineage.
    """
    candidate_id: str = Field(..., description="Foreign key to the candidate profile")
    tenant_id: str = Field(..., description="Tenant ID for RLS")
    
    skill_depth: FeatureValue
    career_progression: FeatureValue
    project_complexity: FeatureValue
    authenticity: FeatureValue
    growth: FeatureValue
    timeline_consistency: FeatureValue
    
    versions: Dict[str, str] = Field(default_factory=dict, description="Pipeline versions used to generate these features")
    
    # Metadata
    updated_at: Optional[str] = Field(None, description="ISO timestamp of last update")
