from typing import List, Optional
from pydantic import BaseModel, Field

class JobProfile(BaseModel):
    """
    Core schema representing a parsed job description.
    This is generated by the Job Intelligence Agent.
    """
    id: Optional[str] = Field(None, description="Unique job ID (UUID)")
    tenant_id: str = Field(..., description="Tenant ID for RLS")
    
    title: str = Field(..., description="Job title")
    department: Optional[str] = Field(None, description="Department or team")
    
    summary: str = Field(..., description="A synthesized summary of the job requirements")
    
    mandatory_skills: List[str] = Field(default_factory=list, description="Strictly required skills")
    nice_to_have_skills: List[str] = Field(default_factory=list, description="Bonus skills")
    
    min_years_experience: float = Field(0.0, description="Minimum years of experience required")
    max_years_experience: Optional[float] = Field(None, description="Maximum years of experience (if specified)")
    
    education_requirement: Optional[str] = Field(None, description="Degree requirements (e.g., Bachelor's, Master's)")
    
    implicit_constraints: List[str] = Field(default_factory=list, description="Extracted constraints like 'startup experience'")
