from typing import Optional
from pydantic import BaseModel, Field

class CandidateRank(BaseModel):
    """
    Schema for the final ranking output.
    Generated by the deterministic Ranking Engine.
    """
    candidate_id: str = Field(..., description="Foreign key to the candidate profile")
    job_id: str = Field(..., description="Foreign key to the job profile")
    
    # The final computed Hiring Relevance Score (HRS)
    final_score: float = Field(0.0, ge=0.0, le=1.0, description="The deterministic Hiring Relevance Score")
    
    # Breakdown of how the score was calculated for auditability
    semantic_score: float = Field(0.0, description="Score from Qdrant vector retrieval")
    evaluation_score: float = Field(0.0, description="Aggregated score from EvaluationResult")
    feature_score: float = Field(0.0, description="Aggregated score from CandidateFeatures")
    
    # Rank position (e.g., 1st, 2nd, 3rd) relative to other candidates evaluated for this job
    rank_position: Optional[int] = Field(None, description="The integer rank relative to the cohort")
